"""empty message

Revision ID: 12e241148001
Revises: 57778f19def4, b3a4a1b2c3d4
Create Date: 2025-07-03 04:28:34.875686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e241148001'
down_revision = ('57778f19def4', 'b3a4a1b2c3d4')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notes_file_id_files', 'files', ['file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notes_file_id_files', type_='foreignkey')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
