"""Add embedding field to Note model

Revision ID: 43a2c1f84601
Revises: 12e241148001
Create Date: 2025-07-08 18:08:03.422302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a2c1f84601'
down_revision = '12e241148001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_cache', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('analysis_cache')

    # ### end Alembic commands ###
