"""Remove task_id from File model

Revision ID: 509a12738447
Revises: d7f1d412bcca
Create Date: 2025-07-03 03:21:47.171581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509a12738447'
down_revision = 'd7f1d412bcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
