"""Change file_metadata to JSON type

Revision ID: 57778f19def4
Revises: 43d17fa9e9d1
Create Date: 2025-07-03 04:22:38.678923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57778f19def4'
down_revision = '43d17fa9e9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('file_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('file_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
