"""Expand processing_status column in files table

Revision ID: 633527158a99
Revises: 509a12738447
Create Date: 2025-07-03 04:04:38.673883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633527158a99'
down_revision = '509a12738447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('processing_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('processing_status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
