"""Change file_metadata to JSON type

Revision ID: b3a4a1b2c3d4
Revises: 633527158a99
Create Date: 2025-07-03 04:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3a4a1b2c3d4'
down_revision = '633527158a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'file_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='file_metadata::json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'file_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               postgresql_using='file_metadata::text')
    # ### end Alembic commands ###
